# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('united kingdom', 'UNITED KINGDOM'), ('united states', 'UNITED STATES'), ('ireland', 'IRELAND'), ('france', 'FRANCE'), ('australia', 'AUSTRALIA')], max_length=40)),
                ('email', models.EmailField(default='test@test.com', max_length=254)),
                ('description', models.CharField(max_length=500)),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
